version: "3.8"

services:
  database_notepad: 
    image: postgres
    container_name: database_notepad
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=notepad
      - POSTGRES_DB=notepad
    volumes:
      - pgdata:/data/postgres 
  app: 
    build: .
    container_name: notepad-api
    ports: 
      - 2000:2000
    volumes:
      - .:/usr/app 
    links: 
      - database_notepad
    depends_on:
      - database_notepad
volumes:
  pgdata:
    driver: local